### ISSUE TITLE
ENV instead of ARG

### ISSUE THREAD

**Issue by flow23** [pwasem/openui5-sdk-docker#2]
Hi,
thank you for the Dockerfile.
Wouldn't it make more sense to use ENV instead of ARG in Dockerfile and .env?

ENV UI5_VERSION 1.67.1
ENV UI5_FILENAME openui5-sdk-${UI5_VERSION}.zip
ENV UI5_URL https://github.com/SAP/openui5/releases/download/${UI5_VERSION}/${UI5_FILENAME} 

Best regards,
Florian

**Comment by pwasem** [comment]
Hi Florian,

https://vsupalov.com/docker-arg-env-variable-guide/

ARG are also known as build-time variables
.
Whereas ENV variables are also available during the build, as soon as you introduce them with an ENV instruction. However, unlike ARG, they are also accessible by containers started from the final image. ENV values can be overridden when starting a container.

So as we only need the version during built-time not during run-time ARG should be fine.

Or is there any benifit? If so please feel free to create a pull request.

**Comment by flow23** [comment]
Good morning,

I had issues while running the build command that the arguments weren't working for the URL. But it seems the URL for the download from SAP is not working, I got a 404 last night.

Best regards,
Florian
