### ISSUE TITLE
getaddrinfo ENOTFOUND nexus.wdf.sap.corp

### ISSUE THREAD

**Issue by zygimantus** [pwasem/openui5-sdk-docker#5]
I cloned and runned your project using `docker-compose up -d --build` and it gave this error:

> yarn install v1.19.1
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> info There appears to be trouble with your network connection. Retrying...
> error An unexpected error occurred: "http://nexus.wdf.sap.corp:8081/nexus/repository/build.releases.npm/fastify/-/fastify-2.9.0.tgz: getaddrinfo ENOTFOUND nexus.wdf.sap.corp".
> info If you think this is a bug, please open a bug report with the information provided in "/home/node/app/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ERROR: Service 'openui5_sdk' failed to build: The command '/bin/sh -c yarn install --production' returned a non-zero code: 1

**Comment by pwasem** [comment]
@zygimantus 
Thank you for reporting this. I have provided a fix. Could you please retest?

**Comment by zygimantus** [comment]
Thank you, @pwasem , now it works.
